"""empty message

Revision ID: 8e1f631e58ab
Revises: 4764a81f2f7c
Create Date: 2022-07-27 08:45:26.611315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1f631e58ab'
down_revision = '4764a81f2f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('flag', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'flag')
    # ### end Alembic commands ###
