"""empty message

Revision ID: a5f332c919d0
Revises: acd5aa1e3b4b
Create Date: 2022-07-25 18:03:29.829541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5f332c919d0'
down_revision = 'acd5aa1e3b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inserttable', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('inserttable', sa.Column('password', sa.String(length=256), nullable=True))
    op.add_column('inserttable', sa.Column('write_api', sa.String(length=32), nullable=True))
    op.add_column('inserttable', sa.Column('read_api', sa.String(length=32), nullable=True))
    op.add_column('inserttable', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('inserttable', 'stateid')
    op.drop_column('inserttable', 'unixtime')
    op.drop_column('inserttable', 'speed')
    op.drop_column('inserttable', 'state')
    op.drop_column('inserttable', 'machineid')
    op.drop_column('inserttable', 'statechange')
    op.drop_column('inserttable', 'extras')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inserttable', sa.Column('extras', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('inserttable', sa.Column('statechange', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('inserttable', sa.Column('machineid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('inserttable', sa.Column('state', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('inserttable', sa.Column('speed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('inserttable', sa.Column('unixtime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('inserttable', sa.Column('stateid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('inserttable', 'status')
    op.drop_column('inserttable', 'read_api')
    op.drop_column('inserttable', 'write_api')
    op.drop_column('inserttable', 'password')
    op.drop_column('inserttable', 'username')
    # ### end Alembic commands ###
